require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project '/Volumes/SANDISK_MAC/MAPD_GITHUB/NEW_GIT_CLONE/StormBreaker_Group4_m3/ios/StormBreaker_Group4_m3.xcodeproj'

platform :ios, '13.2.2'

target 'StormBreaker_Group4_m3' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'StormBreaker_Group4_m3Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'StormBreaker_Group4_m3-tvOS' do
  # Pods for StormBreaker_Group4_m3-tvOS

  target 'StormBreaker_Group4_m3-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
