project '/Volumes/SANDISK_MAC/MAPD_GITHUB/MAPD_F2020/StormBreaker_Group4_m2/ios/StormBreaker_Group4_m2.xcodeproj'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

platform :ios, '10.0'

target 'StormBreaker_Group4_m2' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'StormBreaker_Group4_m2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'StormBreaker_Group4_m2-tvOS' do
  # Pods for StormBreaker_Group4_m2-tvOS

  target 'StormBreaker_Group4_m2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
